# Generated by Django 5.2.9 on 2026-08-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competencies", "0002_preset_templates"),
        ("lms", "0004_enrollment_lessonprogress"),
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ИПР", max_length=300, verbose_name="Название"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("approved", "Согласован"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершён"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_plans",
                        to="orgstructure.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "План развития",
                "verbose_name_plural": "Планы развития",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DevGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Цель")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "target_level",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="Целевой уровень"
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dev_goals",
                        to="competencies.competency",
                        verbose_name="Компетенция",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="idp.developmentplan",
                        verbose_name="План",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель развития",
                "verbose_name_plural": "Цели развития",
                "unique_together": {("plan", "competency")},
            },
        ),
        migrations.CreateModel(
            name="DevAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course", "Курс"),
                            ("task", "Задание"),
                            ("mentoring", "Менторство"),
                            ("reading", "Чтение"),
                            ("practice", "Практика"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Название действия"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Срок"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланировано"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершено"),
                            ("overdue", "Просрочено"),
                        ],
                        default="planned",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dev_actions",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentored_actions",
                        to="orgstructure.employee",
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="idp.devgoal",
                        verbose_name="Цель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие развития",
                "verbose_name_plural": "Действия развития",
                "ordering": ["goal", "id"],
            },
        ),
    ]
