# Generated by Django 5.2.9 on 2026-08-06 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Email получателя"),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя получателя"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("assessment.assigned", "Назначена оценка"),
                            ("assessment.reminder", "Напоминание о дедлайне"),
                            ("assessment.overdue", "Просрочка оценки"),
                            ("assessment.result", "Итоговый отчёт по циклу"),
                            (
                                "feedback.received",
                                "Получена обратная связь/благодарность",
                            ),
                            ("course.assigned", "Назначен курс"),
                            ("manual.broadcast", "Ручная рассылка HR"),
                        ],
                        max_length=64,
                        verbose_name="Событие",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                ("body", models.TextField(verbose_name="Тело")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("assessment.assigned", "Назначена оценка"),
                            ("assessment.reminder", "Напоминание о дедлайне"),
                            ("assessment.overdue", "Просрочка оценки"),
                            ("assessment.result", "Итоговый отчёт по циклу"),
                            (
                                "feedback.received",
                                "Получена обратная связь/благодарность",
                            ),
                            ("course.assigned", "Назначен курс"),
                            ("manual.broadcast", "Ручная рассылка HR"),
                        ],
                        max_length=64,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="Email включён"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="Push включён"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
                "unique_together": {("user", "event")},
            },
        ),
    ]
