# Generated by Django 5.2.9 on 2026-08-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("assessment.assigned", "Назначена оценка"),
                    ("assessment.reminder", "Напоминание о дедлайне"),
                    ("assessment.overdue", "Просрочка оценки"),
                    ("assessment.result", "Итоговый отчёт по циклу"),
                    ("feedback.received", "Получена обратная связь/благодарность"),
                    ("course.assigned", "Назначен курс"),
                    ("course.result", "Результат проверки задания"),
                    ("manual.broadcast", "Ручная рассылка HR"),
                ],
                max_length=64,
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="event",
            field=models.CharField(
                choices=[
                    ("assessment.assigned", "Назначена оценка"),
                    ("assessment.reminder", "Напоминание о дедлайне"),
                    ("assessment.overdue", "Просрочка оценки"),
                    ("assessment.result", "Итоговый отчёт по циклу"),
                    ("feedback.received", "Получена обратная связь/благодарность"),
                    ("course.assigned", "Назначен курс"),
                    ("course.result", "Результат проверки задания"),
                    ("manual.broadcast", "Ручная рассылка HR"),
                ],
                max_length=64,
                verbose_name="Событие",
            ),
        ),
    ]
