# Generated by Django 5.2.9 on 2026-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_pushsubscription"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["event", "recipient_email"], name="notif_event_email_idx"
            ),
        ),
    ]
