# Generated by Django 5.2.9 on 2026-08-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Текстовый материал"), ("quiz", "Тест")],
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Содержание (текст)"),
                ),
                (
                    "pass_score",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="Проходной балл, %"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Максимум попыток"
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, verbose_name="Перемешивать вопросы"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["course", "order", "id"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "Один ответ"),
                            ("multiple", "Несколько ответов"),
                            ("scale", "Шкала"),
                            ("text", "Текстовый ответ"),
                        ],
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Балл"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        limit_choices_to={"type": "quiz"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lms.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["lesson", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="Текст варианта"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="lms.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
                "ordering": ["question", "order", "id"],
            },
        ),
    ]
