# Generated by Django 5.2.9 on 2026-08-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0002_lesson_question_answeroption"),
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Название задания"),
                ),
                ("description", models.TextField(verbose_name="Описание задания")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practical_tasks",
                        to="lms.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_to_review",
                        to="orgstructure.employee",
                        verbose_name="Куратор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Практическое задание",
                "verbose_name_plural": "Практические задания",
                "ordering": ["lesson", "id"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(blank=True, verbose_name="Текст ответа"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Отправлено"),
                            ("in_review", "На проверке"),
                            ("reviewed", "Проверено"),
                        ],
                        default="submitted",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Отправлено"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Проверено"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_submissions",
                        to="orgstructure.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lms.practicaltask",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на задание",
                "verbose_name_plural": "Ответы на задания",
                "ordering": ["-submitted_at"],
                "unique_together": {("task", "employee")},
            },
        ),
        migrations.CreateModel(
            name="TaskReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Зачтено")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Оценка по шкале"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий куратора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_reviews",
                        to="orgstructure.employee",
                        verbose_name="Куратор",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="lms.submission",
                        verbose_name="Ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка задания",
                "verbose_name_plural": "Проверки заданий",
            },
        ),
    ]
