# Generated by Django 5.2.9 on 2026-08-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0004_enrollment_lessonprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Уникальный код"
                    ),
                ),
                (
                    "employee_full_name",
                    models.CharField(max_length=300, verbose_name="ФИО сотрудника"),
                ),
                (
                    "course_title",
                    models.CharField(max_length=300, verbose_name="Название курса"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Выдан"),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="lms.enrollment",
                        verbose_name="Запись на курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "ordering": ["-issued_at"],
            },
        ),
    ]
