# Generated by Django 5.2.9 on 2026-08-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ad_thumbnail_photo",
            field=models.BinaryField(
                blank=True,
                help_text="Копия thumbnailPhoto, обновляемая после успешного LDAP-входа.",
                null=True,
                verbose_name="Фото из AD",
            ),
        ),
    ]
