# Generated by Django 5.2.9 on 2026-08-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course_passed", "Курс пройдён"),
                            ("achievement", "Достижение"),
                            ("project", "Проект/кейс"),
                            ("thank_you", "Благодарность"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_entries",
                        to="orgstructure.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись портфолио",
                "verbose_name_plural": "Записи портфолио",
                "ordering": ["-created_at"],
            },
        ),
    ]
