# Generated by Django 5.2.9 on 2026-08-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
                "ordering": ["group__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompetencyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Группа компетенций",
                "verbose_name_plural": "Группы компетенций",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "min_value",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Минимум"),
                ),
                (
                    "max_value",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Максимум"
                    ),
                ),
            ],
            options={
                "verbose_name": "Шкала",
                "verbose_name_plural": "Шкалы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompetencyFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название модели"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("corporate", "Корпоративная"),
                            ("role", "Ролевая"),
                            ("individual", "Индивидуальная"),
                        ],
                        default="corporate",
                        max_length=16,
                        verbose_name="Тип привязки",
                    ),
                ),
                (
                    "competencies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="frameworks",
                        to="competencies.competency",
                        verbose_name="Компетенции",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frameworks",
                        to="orgstructure.employee",
                        verbose_name="Сотрудник (для индивидуальной модели)",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frameworks",
                        to="orgstructure.position",
                        verbose_name="Должность (для ролевой модели)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель компетенций",
                "verbose_name_plural": "Модели компетенций",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="competency",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competencies",
                to="competencies.competencygroup",
                verbose_name="Группа",
            ),
        ),
        migrations.AddField(
            model_name="competency",
            name="scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competencies",
                to="competencies.scale",
                verbose_name="Шкала",
            ),
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(verbose_name="Уровень шкалы"),
                ),
                ("description", models.TextField(verbose_name="Описание поведения")),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="competencies.competency",
                        verbose_name="Компетенция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поведенческий индикатор",
                "verbose_name_plural": "Поведенческие индикаторы",
                "ordering": ["competency", "level"],
                "unique_together": {("competency", "level")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="competency",
            unique_together={("group", "name")},
        ),
    ]
