# Generated by Django 5.2.9 on 2026-08-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Что хотите обсудить?"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает ответа"),
                            ("answered", "Отвечено"),
                            ("expired", "Просрочено"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отвечено"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_requests_received",
                        to="orgstructure.employee",
                        verbose_name="Получатель ОС",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_requests_sent",
                        to="orgstructure.employee",
                        verbose_name="Запросивший",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос обратной связи",
                "verbose_name_plural": "Запросы обратной связи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Praise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Текст благодарности")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Публичная"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Анонимная"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_praises",
                        to="orgstructure.employee",
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_praises",
                        to="orgstructure.employee",
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Благодарность",
                "verbose_name_plural": "Благодарности",
                "ordering": ["-created_at"],
            },
        ),
    ]
