# Generated by Django 5.2.9 on 2026-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneCSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_successful_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последняя успешная синхронизация",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Изменено в 1С"),
        ),
        migrations.AddField(
            model_name="employee",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Изменено в 1С"),
        ),
        migrations.AddField(
            model_name="position",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Изменено в 1С"),
        ),
    ]
