# Generated by Django 5.2.9 on 2026-08-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competencies", "0002_preset_templates"),
        ("orgstructure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название цикла"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("assigned", "Оценщики назначены"),
                            ("in_progress", "Идёт оценка"),
                            ("collecting", "Сбор ответов завершается"),
                            ("aggregated", "Результаты рассчитаны"),
                            ("closed", "Закрыт"),
                        ],
                        default="created",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "anonymity_threshold",
                    models.PositiveSmallIntegerField(
                        default=3,
                        verbose_name="Порог анонимности (мин. оценщиков в группе)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cycles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycles",
                        to="competencies.competencyframework",
                        verbose_name="Модель компетенций",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цикл оценки",
                "verbose_name_plural": "Циклы оценки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="assessment.assessmentcycle",
                        verbose_name="Цикл",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_participations",
                        to="orgstructure.employee",
                        verbose_name="Оцениваемый сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник цикла",
                "verbose_name_plural": "Участники цикла",
                "unique_together": {("cycle", "employee")},
            },
        ),
        migrations.CreateModel(
            name="ReviewerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("manager", "Руководитель"),
                            ("peer", "Коллега"),
                            ("subordinate", "Подчинённый"),
                            ("self", "Самооценка"),
                        ],
                        max_length=16,
                        verbose_name="Группа оценщиков",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Оценка заполнена"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Заполнена"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_assignments",
                        to="assessment.assessmentcycle",
                        verbose_name="Цикл",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_assignments",
                        to="assessment.participant",
                        verbose_name="Оцениваемый",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_assignments",
                        to="orgstructure.employee",
                        verbose_name="Оценщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение оценщика",
                "verbose_name_plural": "Назначения оценщиков",
            },
        ),
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(verbose_name="Оценка по шкале"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="competencies.competency",
                        verbose_name="Компетенция",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessment.reviewerassignment",
                        verbose_name="Назначение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сырой ответ оценки",
                "verbose_name_plural": "Сырые ответы оценки",
            },
        ),
        migrations.CreateModel(
            name="AssessmentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "is_general",
                    models.BooleanField(
                        default=False,
                        verbose_name="Общий комментарий (не по конкретной компетенции)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="competencies.competency",
                        verbose_name="Компетенция (если комментарий по ней)",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="assessment.reviewerassignment",
                        verbose_name="Назначение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий оценки",
                "verbose_name_plural": "Комментарии оценки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="reviewerassignment",
            constraint=models.UniqueConstraint(
                fields=("cycle", "participant", "reviewer"),
                name="unique_reviewer_per_participant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewerassignment",
            unique_together={("cycle", "participant", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="assessmentresponse",
            index=models.Index(fields=["assignment"], name="resp_assignment_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assessmentresponse",
            unique_together={("assignment", "competency")},
        ),
    ]
