# Generated by Django 5.2.9 on 2026-08-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0001_initial"),
        ("competencies", "0002_preset_templates"),
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpectedLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_level",
                    models.PositiveSmallIntegerField(
                        verbose_name="Ожидаемый уровень шкалы"
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expected_levels",
                        to="competencies.competency",
                        verbose_name="Компетенция",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expected_levels",
                        to="orgstructure.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ожидаемый уровень",
                "verbose_name_plural": "Ожидаемые уровни",
                "unique_together": {("position", "competency")},
            },
        ),
    ]
