# Generated by Django 5.2.9 on 2026-08-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_expectedlevel"),
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Цель")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                            ("YEAR", "Год"),
                        ],
                        default="YEAR",
                        max_length=8,
                        verbose_name="Период",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(default=2026, verbose_name="Год"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активна"),
                            ("completed", "Завершена"),
                            ("overdue", "Просрочена"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives",
                        to="assessment.assessmentcycle",
                        verbose_name="Цикл оценки",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="orgstructure.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель (MBO/OKR)",
                "verbose_name_plural": "Цели (MBO/OKR)",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="KR")),
                (
                    "target_value",
                    models.FloatField(default=100, verbose_name="Целевое значение"),
                ),
                (
                    "current_value",
                    models.FloatField(default=0, verbose_name="Текущее значение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_results",
                        to="assessment.objective",
                        verbose_name="Цель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ключевой результат",
                "verbose_name_plural": "Ключевые результаты",
                "ordering": ["objective", "id"],
            },
        ),
    ]
