# Generated by Django 5.2.9 on 2026-08-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0003_objective_keyresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentAggregateArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Обезличенный агрегат")),
                ("archived_at", models.DateTimeField(auto_now_add=True, verbose_name="Архивирован")),
                (
                    "cycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregate_archive",
                        to="assessment.assessmentcycle",
                        verbose_name="Цикл оценки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Архив агрегата оценки",
                "verbose_name_plural": "Архивы агрегатов оценки",
            },
        ),
    ]
